version: '3.8'
services:
    postgres:
        image: postgres:latest
        container_name: taskmanager_db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: TaskManagerDb
        ports:
        - "5432:5432"